language: go

sudo: false

ignore:
  - Makefile

matrix:
  include:
    - go: "1.8.x"
    - go: "1.9.x"
    - go: "1.10.x"
    - go: "1.11.x"
      env: GO111MODULE=off
    - go: "1.11.x"
      env: GO111MODULE=on
    - go: tip
  script:
    - go test -v -race $(go list ./... | grep -v vendor)